### ISSUE TITLE
Exception when trying to update from Manjaro `pamac` package manager

### ISSUE THREAD

**Issue by pedroxs** [atanunq/viu#37]
Exception when trying to update from Manjaro `pamac` package manager:

```
   Compiling viu v1.0.0 (/tmp/pamac-build/viu/src/viu-1.0)
error: `core::slice::<impl [T]>::len` is not yet stable as a const fn
   --> src/printer.rs:166:5
    |
166 |     buffer.len() == width as usize
    |     ^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `viu`.
```

System info:
```
❯ uname -a
Linux pc15 5.5.10-1-MANJARO #1 SMP PREEMPT Wed Mar 18 11:17:36 UTC 2020 x86_64 GNU/Linux

❯ cargo -V
cargo 1.37.0 (9edd08916 2019-08-02)

❯ viu -V
viu 0.2.2
```

**Comment by atanunq** [comment]
Thank you for reporting!

The problem is that the errenous feature is stable from [Rust 1.39](https://blog.rust-lang.org/2019/11/07/Rust-1.39.0.html#more-const-fns-in-the-standard-library). Therefore, you will need to update your Rust in order to compile it.

I will add a note in the Readme, apologies for the inconvenience!

**Comment by pedroxs** [comment]
Thanks that solved the issue. Interestingly enough `rust` was not updated from Manjaro package manager on my machine, I had to manually run `rustup update` to solve the issue. Leaving the comment here for clarity. 

BTW it was no inconvenience at all and you answered the issue in record breaking time :) 
Thanks for the awesome tool!
