### ISSUE TITLE
Usage with ranger preview

### ISSUE THREAD

**Issue by Boot-Error** [atanunq/viu#6]
I'm trying to get it work with ranger cli file manager, only by replacing the img2txt with viu.
But it gives garbled render of the image. Can you maybe help with a possible solution to this?

Here is `viu` output:
![image](https://user-images.githubusercontent.com/8546140/57198766-61503480-6f94-11e9-844b-28f9f4e8d4d4.png)

Here is `viu` in ranger preview:
![image](https://user-images.githubusercontent.com/8546140/57198792-bc822700-6f94-11e9-87fe-36d65f7bdf91.png)

**Comment by atanunq** [comment]
Hi, thank you for doing this! I looked into it a bit and discovered this [StackOverflow thread](https://stackoverflow.com/questions/1461907/html-encoding-issues-%C3%82-character-showing-up-instead-of-nbsp). It indeed is an encoding issue because even `less` cannot view an image without the `-r` flag as seen below.


![anim](https://user-images.githubusercontent.com/20361395/57199119-43260c80-6f73-11e9-813a-c829efc28bd3.gif)

I am not sure I can help you a lot more with this, as I am not familiar with ranger. However, it might be work looking into `w3m`, the default ranger viewer, as its trying to render HTML and the SO thread states the same. Just a guess, though.

**Comment by atanunq** [comment]
Please feel free to reopen if you would like me to revisit the issue presented above.
